#!/bin/bash

echo 
echo '#############################################################'
echo '##                                                         ##'
echo '## Wait approximately 15 seconds, to allow the VM to boot. ##'
echo '## Then run:  ssh level00@localhost -p 2223                ##'
echo '## Password:  user                                         ##'
echo '##                                                         ##'
echo '#############################################################'
echo

#docker run -itd --name nebula -h nebula --device /dev/kvm --privileged -p 2223:22 -e XDG_RUNTIME_DIR=/tmp \
#    -e WAYLAND_DISPLAY=$WAYLAND_DISPLAY \
#    -e QT_QPA_PLATFORM=wayland \
#    -e GDK_BACKEND=wayland \
#    -e CLUTTER_BACKEND=wayland \
#    -e DISPLAY=:0 \
#    nebula 2>&1 > /dev/null

docker run -itd --name nebula -h nebula --device /dev/kvm --privileged -p 2223:2223 nebula 2>&1 > /dev/null
